"""Command-line utilities for Wizelit SDK."""

from __future__ import annotations

import re
from pathlib import Path
from textwrap import dedent

import click


TRANSPORT_CHOICES = ["streamable-http", "sse", "stdio", "http"]


def _slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    if not value:
        raise click.ClickException("Agent name must contain letters or numbers.")
    return value


def _write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise click.ClickException(
            f"File already exists: {path}. Use --force to overwrite."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _render_main_py(
    agent_name: str, transport: str, host: str, port: int
) -> str:
    return dedent(
        f'''"""Wizelit Agent Scaffold
        Generated by wizelit-agent CLI.
        """

        from wizelit_sdk.agent_wrapper import WizelitAgent

        mcp = WizelitAgent(
            "{agent_name}",
            transport="{transport}",
            host="{host}",
            port={port},
        )


        @mcp.ingest(
            is_long_running=False,
            description="Describe your tool here.",
            response_handling={{"mode": "json"}},
        )
        def example_tool(text: str) -> dict:
            """Example tool."""
            return {{"echo": text}}


        if __name__ == "__main__":
            mcp.run()
        '''
    ).lstrip()


def _render_readme(agent_name: str) -> str:
    return dedent(
        f"""
        # {agent_name}

        Generated Wizelit agent scaffold.

        ## Run

        ```bash
        python main.py
        ```
        """
    ).lstrip()


def _render_env_example() -> str:
    return dedent(
        """
        # Example environment variables
        REDIS_URL=redis://localhost:6379
        ENABLE_LOG_STREAMING=true

        # AWS (if using Bedrock)
        AWS_ACCESS_KEY_ID=
        AWS_SECRET_ACCESS_KEY=
        AWS_REGION=us-east-1
        """
    ).lstrip()


def _render_requirements(template: str) -> str:
    base = ["wizelit-sdk"]
    if template == "fast":
        extras = []
    elif template == "slow":
        extras = ["redis>=4.5.0"]
    else:  # hybrid
        extras = ["redis>=4.5.0"]
    return "\n".join(base + extras) + "\n"


def _render_main_for_template(agent_name: str, template: str) -> str:
    # Fast agent: synchronous/simple
    if template == "fast":
        return dedent(
            f'''
            """Fast Wizelit Agent
            Generated by wizelit CLI
            """

            from wizelit_sdk.agent_wrapper import WizelitAgent

            mcp = WizelitAgent(
                "{agent_name}",
                transport="streamable-http",
            )


            @mcp.ingest(is_long_running=False, description="Fast sync tool")
            def analyze(text: str) -> dict:
                """A fast synchronous tool example."""
                return {{"echo": text}}


            if __name__ == "__main__":
                mcp.run()
            '''
        ).lstrip()

    # Slow agent: long-running async example
    if template == "slow":
        return dedent(
            f'''
            """Slow Wizelit Agent (long-running)
            Generated by wizelit CLI
            """

            import asyncio
            from wizelit_sdk.agent_wrapper import WizelitAgent, Job

            mcp = WizelitAgent(
                "{agent_name}",
                transport="streamable-http",
                enable_streaming=True,
            )


            @mcp.ingest(is_long_running=True, description="Long-running refactor")
            async def long_task(code: str, job: Job) -> dict:
                job.logger.info("Starting long-running task")
                # Simulate work and progress
                for i in range(3):
                    await asyncio.sleep(1)
                    job.logger.info(f"Progress: {{i+1}}/3")
                return {{"result": "done"}}


            if __name__ == "__main__":
                mcp.run()
            '''
        ).lstrip()

    # Hybrid: both examples present
    return dedent(
        f'''
        """Hybrid Wizelit Agent
        Generated by wizelit CLI
        """

        import asyncio
        from wizelit_sdk.agent_wrapper import WizelitAgent, Job

        mcp = WizelitAgent(
            "{agent_name}",
            transport="streamable-http",
            enable_streaming=True,
        )


        @mcp.ingest(is_long_running=False, description="Fast helper")
        def quick(text: str) -> dict:
            return {{"echo": text}}


        @mcp.ingest(is_long_running=True, description="Slow worker")
        async def worker(payload: str, job: Job) -> dict:
            job.logger.info("Hybrid worker starting")
            await asyncio.sleep(1)
            return {{"status": "ok"}}


        if __name__ == "__main__":
            mcp.run()
        '''
    ).lstrip()


@click.group()
def cli() -> None:
    """Wizelit SDK command-line tools."""


@cli.command("scaffold")
@click.argument("name")
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=Path.cwd(),
    show_default="current directory",
)
@click.option(
    "--transport",
    type=click.Choice(TRANSPORT_CHOICES),
    default="streamable-http",
    show_default=True,
)
@click.option("--host", default="0.0.0.0", show_default=True)
@click.option("--port", default=8080, show_default=True, type=int)
@click.option("--force", is_flag=True, help="Overwrite existing files.")
def scaffold(
    name: str,
    output_dir: Path,
    transport: str,
    host: str,
    port: int,
    force: bool,
) -> None:
    """Scaffold a new Wizelit agent project."""
    slug = _slugify(name)
    project_dir = output_dir / slug

    project_dir.mkdir(parents=True, exist_ok=True)

    _write_file(project_dir / "main.py", _render_main_py(name, transport, host, port), force)
    _write_file(project_dir / "README.md", _render_readme(name), force)
    _write_file(
        project_dir / "requirements.txt",
        "wizelit-sdk\n",
        force,
    )

    click.echo(f"✅ Scaffold created at: {project_dir}")
    click.echo("Next steps:")
    click.echo("  1) Install dependencies: pip install -r requirements.txt")
    click.echo("  2) Run the agent: python main.py")


@cli.command("init")
@click.argument("name")
@click.option("--template", type=click.Choice(["fast", "slow", "hybrid"]), default="fast")
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=Path.cwd(),
    show_default="current directory",
)
@click.option("--force", is_flag=True, help="Overwrite existing files.")
def init(name: str, template: str, output_dir: Path, force: bool) -> None:
    """Initialize a new Wizelit agent project using a template."""
    slug = _slugify(name)
    project_dir = output_dir / slug
    project_dir.mkdir(parents=True, exist_ok=True)

    # Write main.py for the selected template
    _write_file(project_dir / "main.py", _render_main_for_template(name, template), force)
    _write_file(project_dir / "README.md", _render_readme(name), force)
    _write_file(project_dir / "requirements.txt", _render_requirements(template), force)
    _write_file(project_dir / ".env.example", _render_env_example(), force)

    click.echo(f"✅ Project initialized at: {project_dir}")
    click.echo("Next steps:")
    click.echo("  1) Install dependencies: pip install -r requirements.txt")
    click.echo("  2) Run the agent: python main.py")


@cli.command("validate")
@click.argument("path", type=click.Path(file_okay=True, dir_okay=True, path_type=Path), default=Path.cwd())
def validate(path: Path) -> None:
    """Validate a Wizelit agent project structure."""
    if path.is_file():
        project_dir = path.parent
    else:
        project_dir = path

    required = ["main.py", "requirements.txt", "README.md"]
    missing = [p for p in required if not (project_dir / p).exists()]
    if missing:
        click.echo(f"❌ Missing files: {missing}")
        raise click.Abort()
    click.echo("✅ Project looks valid")


@cli.command("list-tools")
@click.argument("path", type=click.Path(file_okay=True, dir_okay=True, path_type=Path), default=Path.cwd())
def list_tools(path: Path) -> None:
    """List tools (functions decorated with @mcp.ingest) in a project."""
    if path.is_file():
        project_dir = path.parent
    else:
        project_dir = path

    py_files = list(project_dir.glob("*.py"))
    tools = []
    for f in py_files:
        text = f.read_text(encoding="utf-8")
        if "@mcp.ingest" in text:
            # naive extraction: look for def <name>( after decorator
            for line in text.splitlines():
                if line.strip().startswith("def "):
                    name = line.strip().split()[1].split("(")[0]
                    tools.append((f.name, name))

    if not tools:
        click.echo("No tools found (no @mcp.ingest decorators detected).")
        return

    for file, name in tools:
        click.echo(f"- {name} (in {file})")


def main() -> None:
    cli()


if __name__ == "__main__":
    main()
