"""Command-line utilities for Wizelit SDK."""

from __future__ import annotations

import re
from pathlib import Path
from textwrap import dedent

import click


TRANSPORT_CHOICES = ["streamable-http", "sse", "stdio", "http"]


def _slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    if not value:
        raise click.ClickException("Agent name must contain letters or numbers.")
    return value


def _write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise click.ClickException(
            f"File already exists: {path}. Use --force to overwrite."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _render_main_py(
    agent_name: str, transport: str, host: str, port: int
) -> str:
    return dedent(
        f'''"""Wizelit Agent Scaffold
        Generated by wizelit-agent CLI.
        """

        from wizelit_sdk.agent_wrapper import WizelitAgent

        mcp = WizelitAgent(
            "{agent_name}",
            transport="{transport}",
            host="{host}",
            port={port},
        )


        @mcp.ingest(
            is_long_running=False,
            description="Describe your tool here.",
            response_handling={{"mode": "json"}},
        )
        def example_tool(text: str) -> dict:
            """Example tool."""
            return {{"echo": text}}


        if __name__ == "__main__":
            mcp.run()
        '''
    ).lstrip()


def _render_readme(agent_name: str) -> str:
    return dedent(
        f"""
        # {agent_name}

        Generated Wizelit agent scaffold.

        ## Run

        ```bash
        python main.py
        ```
        """
    ).lstrip()


@click.group()
def cli() -> None:
    """Wizelit SDK command-line tools."""


@cli.command("scaffold")
@click.argument("name")
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=Path.cwd(),
    show_default="current directory",
)
@click.option(
    "--transport",
    type=click.Choice(TRANSPORT_CHOICES),
    default="streamable-http",
    show_default=True,
)
@click.option("--host", default="0.0.0.0", show_default=True)
@click.option("--port", default=8080, show_default=True, type=int)
@click.option("--force", is_flag=True, help="Overwrite existing files.")
def scaffold(
    name: str,
    output_dir: Path,
    transport: str,
    host: str,
    port: int,
    force: bool,
) -> None:
    """Scaffold a new Wizelit agent project."""
    slug = _slugify(name)
    project_dir = output_dir / slug

    project_dir.mkdir(parents=True, exist_ok=True)

    _write_file(project_dir / "main.py", _render_main_py(name, transport, host, port), force)
    _write_file(project_dir / "README.md", _render_readme(name), force)
    _write_file(
        project_dir / "requirements.txt",
        "wizelit-sdk\n",
        force,
    )

    click.echo(f"✅ Scaffold created at: {project_dir}")
    click.echo("Next steps:")
    click.echo("  1) Install dependencies: pip install -r requirements.txt")
    click.echo("  2) Run the agent: python main.py")


def main() -> None:
    cli()


if __name__ == "__main__":
    main()
